name: Security Scan

on:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'requirements*.txt'
      - 'pyproject.toml'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety pip-audit
        pip install -e .

    - name: Run bandit security scan
      run: |
        echo "Running Bandit security scan..."
        bandit -r src/featureflagshq/ -f json -o bandit-report.json || true
        bandit -r src/featureflagshq/ || echo "Bandit found security issues"

    - name: Run safety check
      run: |
        echo "Running Safety check..."
        safety check --json --output safety-report.json || true
        safety check || echo "Safety found vulnerable dependencies"

    - name: Run pip-audit
      run: |
        echo "Running pip-audit..."
        pip-audit --format=json --output=pip-audit-report.json || true
        pip-audit || echo "pip-audit found issues"

    - name: Upload security reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          bandit-report.json
          safety-report.json
          pip-audit-report.json
        retention-days: 30

    - name: Security scan summary
      if: always()
      run: |
        echo "## Security Scan Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Security scan completed. Check the uploaded artifacts for detailed reports." >> $GITHUB_STEP_SUMMARY
        
        if [ -f bandit-report.json ]; then
          echo "- ✅ Bandit scan completed" >> $GITHUB_STEP_SUMMARY
        fi
        
        if [ -f safety-report.json ]; then
          echo "- ✅ Safety scan completed" >> $GITHUB_STEP_SUMMARY
        fi
        
        if [ -f pip-audit-report.json ]; then
          echo "- ✅ Pip-audit scan completed" >> $GITHUB_STEP_SUMMARY
        fi